import express from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import courseRoutes from './courseRoutes.js';
import lessonRoutes from './lessonRoutes.js';
import resourceRoutes from './resourceRoutes.js';
import quizRoutes from './quizRoutes.js';
import questionRoutes from './questionRoutes.js';
import quizAttemptRoutes from './quizAttemptRoutes.js';
import assignmentRoutes from './assignmentRoutes.js';
import submissionRoutes from './submissionRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import commentRoutes from './commentRoutes.js';
import courseReviewRoutes from './courseReviewRoutes.js';
import eventRoutes from './eventRoutes.js';
import progressRoutes from './progressRoutes.js';
import adminLogRoutes from './adminLogRoutes.js';
import certificateRoutes from './certificateRoutes.js';
import { protect } from '../middleware/authMiddleware.js';
import { isNotStudent } from '../middleware/roleMiddleware.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/user', userRoutes);
router.use('/course', protect, isNotStudent, courseRoutes);
router.use('/lesson', protect, isNotStudent, lessonRoutes);
router.use('/resource', protect, isNotStudent, resourceRoutes);
router.use('/quiz', protect, isNotStudent, quizRoutes);
router.use('/question', protect, isNotStudent, questionRoutes);
router.use('/attempt', protect, isNotStudent, quizAttemptRoutes);
router.use('/assignment', protect, isNotStudent, assignmentRoutes);
router.use('/submission', protect, isNotStudent, submissionRoutes);
router.use('/notification', protect, isNotStudent, notificationRoutes);
router.use('/comment', protect, isNotStudent, commentRoutes);
router.use('/review', protect, isNotStudent, courseReviewRoutes);
router.use('/event', protect, isNotStudent, eventRoutes);
router.use('/progress', progressRoutes);
router.use('/log', adminLogRoutes);
router.use('/certificate', certificateRoutes); 

export default router;
